### ISSUE TITLE
does not comment correctly

### ISSUE THREAD

**Issue by yoexpertz** [DuarteDx/InstagramFirstCommenter#1]
Instead of commenting as soon as the person posts, it comments on the recent post and it keeps on repeating.

update: new issue, it does not click "log in" button.

**Comment by Noah-pixel** [comment]
> Instead of commenting as soon as the person posts, it comments on the recent post and it keeps on repeating.
> 
> update: new issue, it does not click "log in" button.

Yeah that's true, did you find anything related to this? I'm also searching for a bot like this. Hit me up.

**Comment by nanowell** [comment]
> > Instead of commenting as soon as the person posts, it comments on the recent post and it keeps on repeating.
> > update: new issue, it does not click "log in" button.
> 
> Yeah that's true, did you find anything related to this? I'm also searching for a bot like this. Hit me up.

if you did hit me up too :)

**Comment by Noah-pixel** [comment]
> > > Instead of commenting as soon as the person posts, it comments on the recent post and it keeps on repeating.
> > > update: new issue, it does not click "log in" button.
> > 
> > 
> > Yeah that's true, did you find anything related to this? I'm also searching for a bot like this. Hit me up.
> 
> if you did hit me up too :)

Not yet bro, I'm still doing my research but it's hard to find it, if you did it hit me up

**Comment by duartefdias** [comment]
@yoexpertz, @Noah-pixel, @gra1w 

Fixed login issue :white_check_mark:

@yoexpertz, you need to change the numberOfPostsOnTargetProfile variable before running the script.
If your target page currently has 100 posts you need to change the variable value to 100 before running the script, otherwise the script will continue to post comments at each iteration.
