### ISSUE TITLE
only repeats recent post instead of refreshing

### ISSUE THREAD

**Issue by darklord72** [DuarteDx/InstagramFirstCommenter#2]
i have observed if the posts are like more than 1000 , then instead of waiting it keeps commenting on the most recent pic again and again! any fix for this?

**Comment by duartefdias** [comment]
@darklord72 did you change the "numberOfPostsOnTargetProfile " prior to starting the script?

What the script does is compare the actual number of posts on the page to this variable, if these 2 values are different, a comment will be made and "numberOfPostsOnTargetProfile " is incremented.
