### ISSUE TITLE
error wait a few minutes

### ISSUE THREAD

**Issue by andrewBotBoi** [DuarteDx/InstagramFirstCommenter#3]
after a hundred iterations i couldn't access instagram anymore and i don't know why

**Comment by duartefdias** [comment]
What happens?
Do you get any error message?
@andrewBotBoi

**Comment by andrewBotBoi** [comment]
i did some looking around and if you refresh too many times ig assumes that you're a bot and just forbids you from using ig for a certain period of time

**Comment by duartefdias** [comment]
@andrewBotBoi 
Still going strong after 202 iterations:

![image](https://user-images.githubusercontent.com/24175831/89081601-8c862700-d383-11ea-9a39-d9f078acf495.png)

I didn't find any documentation or reports of instagram banning based on page refreshes.
Please share in case you do.
I noticed that on rare occasions the page takes a few more seconds to load but it eventually loads and continues the process.

In case you continue to get errors, run the script with the chrome network traces open to collect logs.
You can open the network tools as mentioned here:
https://developers.google.com/web/tools/chrome-devtools/network#open
If you manage to capture the traces, download the .har file and share it here.
Additionally, if you have any relevant screenshots also share them here.

**Comment by duartefdias** [comment]
Bot continues to work correctly after 300+ iterations
